# Generated by Django 5.1.3 on 2024-11-16 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_compra_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='creado_en',
        ),
    ]
