# Generated by Django 5.1.3 on 2024-11-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_remove_producto_actualizado_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='precio_total',
            new_name='total',
        ),
    ]
