# Generated by Django 5.1.3 on 2024-11-18 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_rename_precio_unitario_compra_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='total',
        ),
        migrations.AddField(
            model_name='compra',
            name='costo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
