# Generated by Django 5.1.3 on 2024-12-13 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_remove_compra_total_compra_costo_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='boleta',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
