# Generated by Django 5.1.3 on 2024-12-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_venta_boleta_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='boleta',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
