# Generated by Django 5.1.3 on 2024-12-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_alter_venta_boleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
